name: CI

on: [push, pull_request, deployment_status]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - name: Dump GitHub context
        if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Run snapshot tests
        run: npm run test:ci
        env:
          TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
